baseURL = 'https://nahue-passano.github.io/blog/'
languageCode = 'en-us'
title = 'nahue-passano Blog'
theme = 'LoveIt'
enableEmoji = true

[params.home.profile]
  enable = true
  gravatarEmail = ""
  avatarURL = "https://nahue-passano.github.io/assets/img/profile-img.jpg"
  title = "Audio DSP & Machine Learning Engineer"
  subtitle = ""
  typeit = true
  social = true
  disclaimer = ""
[params.header.title]
  name = "nahue-passano's Blog"
[params.page.math]
  enable = true
  # default inline delimiter is $ ... $ and \( ... \)
  # 默认行内定界符是 $ ... $ 和 \( ... \)
  inlineLeftDelimiter = ""
  inlineRightDelimiter = ""
  # default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
  # 默认块定界符是 $$ ... $$, \[ ... \],  \begin{equation} ... \end{equation} 和一些其它的函数
  blockLeftDelimiter = ""
  blockRightDelimiter = ""
  # KaTeX extension copy_tex
  # KaTeX 插件 copy_tex
  copyTex = true
  # KaTeX extension mhchem
  # KaTeX 插件 mhchem
  mhchem = true
[params.page.share]
  enable = true
  Twitter = true
  Facebook = true
  Linkedin = true
  Whatsapp = true
  Pinterest = false
  Tumblr = false
  HackerNews = false
  Reddit = false
  VK = false
  Buffer = false
  Xing = false
  Line = false
  Instapaper = false
  Pocket = false
  Flipboard = false
  Weibo = false
  Blogger = false
  Baidu = false
  Odnoklassniki = false
  Evernote = false
  Skype = false
  Trello = false
  Mix = false

# Author config
[author]
  name = "Nahuel Passano"
  email = "nahue.passano@gmail.com"
  link = "https://linkedin.com/in/nahuelpassano"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "about"
    pre = ""
    post = ""
    name = "About me"
    url = "/about/"
    title = ""
# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark.renderer]
    unsafe=true

defaultContentLanguage = "en"
[languages]
  [languages.en]
    weight = 1
    title = ""
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
    [[languages.en.menu.main]]
      weight = 2
      identifier = "about"
      pre = ""
      post = ""
      name = "About me"
      url = "/about/"
      title = ""
  [languages.es]
    weight = 2
    title = ""
    languageCode = "es"
    languageName = "Español"
    [[languages.es.menu.main]]
      weight = 1
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
    [[languages.es.menu.main]]
      weight = 2
      identifier = "about"
      pre = ""
      post = ""
      name = "Bio"
      url = "/about/"
      title = ""

[params.social]
  github="nahue-passano"
  linkedin="nahuelpassano"
